/* Auto-generated consolidated struct header for AST resolution */
/* Generated by: collect.py --output-header */

/* source: ase_net_port.h */
struct ase_net_port_ops {
    void (*switch_proxy)(struct ase_net_port *port);
        void (*connect_peer)(struct ase_net_port *port, struct ase_net_port *peer);
        void (*set_force_close)(struct ase_net_port *port, int on);
        void (*set_sess_ttl)(struct ase_net_port *port, uint32_t ttl, enum ase_sess_ttl_type type);
        uint32_t (*get_sess_ttl)(struct ase_net_port *port);
        uint32_t (*get_last_hit_time)(struct ase_net_port *port);
        void (*close_cap_pkt)(struct ase_net_port *port);
        bool (*has_data2send)(struct ase_net_port *port);
        int (*get_fd)(struct ase_net_port *port); 
        uint32_t (*clean_pkt_holding_cnt)(struct ase_net_port *port);
        void (*clean_pkt_trace)(struct ase_net_port *port);
        void (*set_quicack)(struct ase_net_port *port);
        void (*block)(struct ase_net_port *port);
        void (*pkts_drop)(struct ase_net_port *port);
};

/* source: ase_net_port.h */
struct ase_net_port {
    void *data;
        const struct ase_net_port_ops *ops;
};

/* source: bitfield_struct.h */
struct BitFieldDevice {
    unsigned int status   : 4;   
        unsigned int mode     : 2;   
        unsigned int reserved : 2;   
        unsigned int channel  : 8;   
        unsigned int enabled  : 1;   
        int          error_code;      
        unsigned int priority : 3;   
        unsigned int : 0;            
        unsigned int flags    : 12;
};

/* source: bitfield_struct.h */
typedef struct stNGE_CFGFILE {
    char *pcKeyEn;
        char *pcKeyCh;
        char *pcDefaultValue;
        uint32_t uiModType;
        uint32_t uiModSpecType;
        uint32_t uiParseState : 1, uiIsNeedCheck : 1, uiIsNeedShow : 1, uiReserve : 29;
} NGE_CFGFILE_S;

/* source: bitfield_struct.h */
typedef struct {
    unsigned int a : 2;
        unsigned int b : 6;
        int          c;         
        unsigned int d : 4;
} DeviceConfig;

/* source: bitfield_struct.h */
typedef struct TaggedSensor {
    unsigned int id     : 8;
        unsigned int active : 1;
        float        value;
} Sensor;

/* source: bitfield_struct.h */
struct ase_sink {
    char *buf;
        uint32_t len;
};

/* source: bitfield_struct.h */
struct ase_buf {
    char *data;
        uint32_t len;
};

/* source: bitfield_struct.h */
struct ase_tcp_port {
    uint32_t close_state[2];
    
        struct list_head tasks;
        struct list_head write_tasks;
        struct list_head sup_timer;
        struct list_head aging_timer;
        struct ase_port net_port;
        const struct ase_tcp_port_ops *sk_ops;
    
        struct ase_sink in;
        struct ase_sink *out;
        struct ase_mem *mem;
        struct ase_sess_caps *caps;
        struct ase_session_ctx *sess_ctx;
        struct {
            struct ase_tcp_port *psp;
            struct ase_sink in;
            struct ase_sink *out;
        } peer;
        struct ase_slink;
        struct ase_pkt_stats pkt_stat;
        struct sched_ent *se;
        struct ase_buf sndbuf;
    
        uint64_t rcv_bytes;
        uint64_t snd_bytes;
        uint32_t drop_bytes;
        uint32_t start_time;
        uint32_t ttl;
        uint16_t ref_cnt;
        uint8_t processing;
        uint8_t inc_pkttl;
    
        enum ase_tcp_port_state state;
        struct ase_timer_list cur_timer_list;
        ase_tcp_port_timeout_action timeout_action;
    
        enum bypass : 1;
        bool write_brake : 1;
        bool bypassing_bypass : 1;
        bool client : 1;
        bool waiting : 1;
        bool unspecified_ttl : 1;
        bool is_udp : 1;
        bool switching_proxy : 1;
        bool switch_proxy_done : 1;
        bool reg_svr_map : 1;
        bool not_need_cap_pkt : 1;
        bool need_more_data : 1;
        bool wait_stack_write : 1;
        bool close_stack_read : 1;
        bool close_read_by_app : 1;
        bool close_write_by_net : 1;
        bool close_write_by_nt : 1;
        bool first_pkt_procd : 1;
        bool proxy_mode : 1;
        bool cache_buf_err : 1;
        bool ignore_upper_data : 1;
        bool disable_pfd_check : 1;
        bool no_need_check_pkt_drop : 1;
        bool bypass_ase_only : 1;
        bool need_check_pkt_hold_too_long : 1;
};

/* source: bitfield_struct.h */
typedef struct {
    struct ase_tcp_port *psp;
            struct ase_sink in;
            struct ase_sink *out;
} peer;

/* source: bitfield_struct.h */
struct ase_net_port_ops {
    void (*switch_proxy)(struct ase_net_port *port);
        void (*connect_peer)(struct ase_net_port *port, struct ase_net_port *peer);
        void (*set_force_close)(struct ase_net_port *port, int on);
        void (*set_sess_ttl)(struct ase_net_port *port, uint32_t ttl, enum ase_sess_ttl_type type);
        uint32_t (*get_sess_ttl)(struct ase_net_port *port);
        uint32_t (*get_last_hit_time)(struct ase_net_port *port);
        void (*close_cap_pkt)(struct ase_net_port *port);
        bool (*has_data2send)(struct ase_net_port *port);
        int (*get_fd)(struct ase_net_port *port); 
        uint32_t (*clean_pkt_holding_cnt)(struct ase_net_port *port);
        void (*clean_pkt_trace)(struct ase_net_port *port);
        void (*set_quicack)(struct ase_net_port *port);
        void (*block)(struct ase_net_port *port);
        void (*pkts_drop)(struct ase_net_port *port);
};

/* source: bitfield_struct.h */
struct ase_net_port {
    void *data;
        const struct ase_net_port_ops *ops;
};

/* source: bitfield_struct.h */
struct ase_listener_material {
    uint32_t vrf;
        uint32_t no_syn_cookie : 1, reserve : 31;
};

