from __future__ import annotations

import argparse
import sys
from pathlib import Path

from .models import SharedVariable
from .utils import find_shared_variables, dump_shared_variables
from .instrument import instrument_code


def _format_variable(variable: SharedVariable) -> str:
    return f"{variable.file}:{variable.line} [{variable.kind}] {variable.name} -> {variable.declaration}"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Identify shared variables in C/C++ source files.")
    parser.add_argument("paths", nargs="+", help="Files or directories to scan")
    parser.add_argument(
        "-r", "--recursive", action="store_true", default=False,
        help="Recursively scan directories")
    parser.add_argument(
        "--json", action="store_true", default=False,
        help="Output results as JSON")
    parser.add_argument(
        "--instrument", action="store_true", default=False,
        help="Instrument code with SIM_FLUSH calls for shared variables")
    parser.add_argument(
        "-I", "--include", action="append", default=[],
        help="Add an include directory for Clang AST parsing")
    parser.add_argument(
        "--conservative-ptr", action="store_true", default=False,
        help="Treat all pointer-typed function parameters as potential shared variables")
    parser.add_argument(
        "--post-if-flush", action="store_true", default=False,
        help="Insert a SIM_FLUSH after every if/else-if/else chain")
    parser.add_argument(
        "--bitfield-map", default=None,
        help="Path to JSON bitfield map file (skip bit-field members that cannot take address)")
    parser.add_argument(
        "--struct-header", default=None,
        help="Path to consolidated struct header (generated by collect.py --output-header), force-included during AST parsing for better type resolution")
    parser.add_argument(
        "--temp-flush", action="store_true", default=False,
        help="Enable source-level fallback: scan for shared variable member accesses missed by clang, instrument with SIM_FLUSH_TEMP")
    parser.add_argument(
        "--inter-ptr-flush", action="store_true", default=False,
        help="Insert SIM_FLUSH_INTER_PTR for intermediate pointer dereferences in chained accesses")
    parser.add_argument(
        "-o", "--output-dir", default=None,
        help="Directory for instrumented output file (default: same directory as source)")
    parser.add_argument(
        "--engine", choices=["tokenize", "regex"], default="tokenize",
        help="Fallback engine for source-level access detection: 'tokenize' (lexical analysis, default) or 'regex' (legacy pattern matching)")
    args = parser.parse_args(argv)

    if args.instrument:
        if len(args.paths) != 1:
            print("Error: --instrument requires exactly one file path")
            return 1
        path = Path(args.paths[0])
        if not path.is_file():
            print(f"Error: {path} is not a file")
            return 1
        try:
            source = path.read_text(encoding="utf-8")
        except OSError as e:
            print(f"Error reading file: {e}")
            return 1
        instrumented = instrument_code(source, str(path), path, include_paths=args.include, conservative_ptr=args.conservative_ptr, post_if_flush=args.post_if_flush, bitfield_map_path=args.bitfield_map, struct_header_path=args.struct_header, temp_flush=args.temp_flush, inter_ptr_flush=args.inter_ptr_flush, engine=args.engine)
        output_name = f"{path.stem}_result{path.suffix}"
        if path.stem.endswith("_bak"):
            output_name = f"{path.stem}{path.suffix}"
        if args.output_dir:
            output_path = Path(args.output_dir) / output_name
            output_path.parent.mkdir(parents=True, exist_ok=True)
        else:
            output_path = path.with_name(output_name)
        try:
            output_path.write_text(instrumented, encoding="utf-8")
        except OSError as e:
            print(f"Error writing output file: {e}")
            return 1
        print(f"Instrumented output written to: {output_path}")
        return 0

    variables = find_shared_variables(args.paths, recursive=args.recursive)
    if args.json:
        print(dump_shared_variables(variables))
        return 0

    if not variables:
        print("No shared variables found.")
        return 0

    for variable in variables:
        print(_format_variable(variable))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
